### PR TITLE
Interest Calculator

### PR DESCRIPTION
**Pull request by charg960**
Temporary JFrame for our calculators.

### CODE REVIEW

**Comment by charg960** [comment]
Request to commit the first version of the Interest Calculator. Result display and accounting for inflation still in progress.

**Review by cloveday098 — COMMENTED** [review]
Is this a JFrame or a class?

**Comment by charg960** [comment]
It's a request to submit my class for interest calculations. The Jframe was our temporary form but the request to delete that is in there, too. Sorry about that!

**Comment by cloveday098** [comment]
No worries, I made a temporary JForm for it. If I have time tonight, I'll try implementing the UI wo/ Jframes.

**Pull request merged**
